/**
 * Publications for the GW Center for Global Mental Health.
 *
 * Two sources, merged on DOI:
 *
 *   1. The Center's own /publications listing (19 entries). These carry the
 *      Center's curated `summary` and its `projects` links, and are flagged
 *      `center: true` so the page can lead with them.
 *   2. The wider recent record of the Center's director, Brandon A. Kohrt
 *      (ORCID 0000-0002-3829-4820), from OpenAlex — every work from 2023
 *      onward. Google Scholar has no API and blocks automated access, so
 *      OpenAlex is used instead: it is an open bibliographic database covering
 *      the same literature with verifiable DOIs, citation counts and
 *      open-access status.
 *
 * 17 of the Center's 19 appear in both and are deduplicated by DOI; the two
 * that do not (a Springer reference-work chapter with no DOI, and one article
 * indexed outside the window) are kept from the Center listing.
 *
 * Peer-review records, datasets, errata, preprints and conference abstracts
 * are excluded — OpenAlex types them alongside publications, but they are not
 * publications. `citations` and `openAccess` are point-in-time values from
 * OpenAlex, captured 2026-08-09; they drift and are not re-fetched at runtime.
 *
 * `theme` is the one derived field: it is keyword-matched from the title and
 * summary into six coarse buckets, because OpenAlex's own topic taxonomy is
 * too granular to filter by (55 journals and a long tail of single-work
 * topics across this set). It is a navigation aid, not an authoritative
 * classification.
 *
 * `authors` holds at most the first six names; `authorCount` is the true
 * total, which reaches 150 on one meta-analysis.
 */

/** Coarse, keyword-derived subject buckets. See the note above. */
export type PublicationTheme =
  | "Training & competency"
  | "Adolescent & child"
  | "Stigma & discrimination"
  | "Measurement & validation"
  | "Maternal & perinatal"
  | "Care delivery & systems";

export type PublicationKind = "Article" | "Review" | "Chapter" | "Editorial";

export type Publication = {
  slug: string;
  title: string;
  /** At most six names; see `authorCount` for the true total. */
  authors: string[];
  authorCount: number;
  journal: string;
  /** ISO date, `YYYY-MM-DD`. */
  date: string;
  year: number;
  doi?: string;
  /** OpenAlex citation count, captured 2026-08-09. */
  citations: number;
  openAccess: boolean;
  kind: PublicationKind;
  /** Appears on the Center's own publications listing. */
  center: boolean;
  /** Center projects this work belongs to, where the listing names them. */
  projects?: string[];
  /** The Center's curated description; only present for `center` entries. */
  summary?: string;
  theme: PublicationTheme;
};

/** Facet order: most-published first, matching the portfolio's weight. */
export const PUBLICATION_THEMES: PublicationTheme[] = [
  "Care delivery & systems",
  "Adolescent & child",
  "Training & competency",
  "Stigma & discrimination",
  "Measurement & validation",
  "Maternal & perinatal",
];

export const PUBLICATIONS: Publication[] = [
  {
    slug: "feasibility-acceptability-and-pilot-effectiveness-of-a-social-contact",
    title: "Feasibility, acceptability, and pilot effectiveness of a social-contact-based intervention to reduce mental health-related stigma among primary care providers in China, Ethiopia, India, Nepal, and Tunisia: Findings from a multi-site pre-post study",
    authors: ["Dristy Gurung", "Bethel Ayele", "Ioannis Bakolis", "Kalpana Bhattarai", "Elaine Brohan", "Anish V. Cherian"],
    authorCount: 28,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2026-08-05",
    year: 2026,
    doi: "https://doi.org/10.1017/gmh.2026.10280",
    citations: 0,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Stigma & discrimination",
  },
  {
    slug: "optimising-and-personalising-task-shared-psychosocial-interventions-fo",
    title: "Optimising and personalising task-shared psychosocial interventions for common mental disorders: a Bayesian component network meta-analysis of individual participant data",
    authors: ["Davide Papola", "Federico Tedeschi", "Orestis Efthimiou", "Mathias Harrer", "Jinane Abi Ramia", "Ceren Acart\u00fcrk"],
    authorCount: 39,
    journal: "The Lancet Psychiatry",
    date: "2026-08-01",
    year: 2026,
    doi: "https://doi.org/10.1016/s2215-0366(26)00193-8",
    citations: 1,
    openAccess: false,
    kind: "Review",
    center: false,
    theme: "Training & competency",
  },
  {
    slug: "an-evaluation-of-non-specialist-training-and-delivery-of-a-brief-cogni",
    title: "An evaluation of non-specialist training and delivery of a brief cognitive-behavioral therapy-based transdiagnostic intervention for adolescents with depression and anxiety in Nairobi, Kenya",
    authors: ["Teresia Mutavi", "Tessa Concepcion", "Mansurat Raji", "Anne Mbwayo", "Stella Waruinge", "Shannon Dorsey"],
    authorCount: 11,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2026-07-29",
    year: 2026,
    doi: "https://doi.org/10.1017/gmh.2026.10273",
    citations: 0,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Training & competency",
  },
  {
    slug: "the-science-of-child-and-adolescent-mental-health-in-brazil-a-nationwi",
    title: "The science of child and adolescent mental health in Brazil: a nationwide systematic review and compendium of evidence-based resources",
    authors: ["Lauro Estivalete Marchionatti", "Andr\u00e9 Cardoso Campello", "Jessica Azevedo Veronesi", "Carolina Ziebold", "Andr\u00e9 Comiran Tonon", "C Casella"],
    authorCount: 27,
    journal: "BMJ Global Health",
    date: "2026-07-01",
    year: 2026,
    doi: "https://doi.org/10.1136/bmjgh-2024-018542",
    citations: 3,
    openAccess: true,
    kind: "Review",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "perspectives-on-non-specialist-training-for-mental-health-care-deliver",
    title: "Perspectives on non-specialist training for mental health care delivery in South Africa: the importance of common factors",
    authors: ["Alexandra L. Rose", "Helen E. Jack", "Latonya Aaron", "Yuche Jacobs", "Nonceba Ciya", "Sibabalwe Ndamase"],
    authorCount: 12,
    journal: "SSM - Mental Health",
    date: "2026-05-16",
    year: 2026,
    doi: "https://doi.org/10.1016/j.ssmmh.2026.100655",
    citations: 0,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Training & competency",
  },
  {
    slug: "exploring-gpt-based-models-for-depression-detection-in-adolescents-usi",
    title: "Exploring GPT-based models for depression detection in adolescents using naturalistic speech: A proof-of-concept study",
    authors: ["Anna Viduani", "Leonardo Z. Ferreira", "Claudia Buchweitz", "Jader Piccin", "Helen L. Fisher", "Alastair van Heerden"],
    authorCount: 10,
    journal: "Journal of Affective Disorders",
    date: "2026-05-13",
    year: 2026,
    doi: "https://doi.org/10.1016/j.jad.2026.121956",
    citations: 1,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "longitudinal-transcriptomic-profiles-associated-with-onset-and-remissi",
    title: "Longitudinal transcriptomic profiles associated with onset and remission of adolescent depression",
    authors: ["Valentina Zonca", "Samantha Saleri", "M. Marizzoni", "Pedro H. Manfro", "Naghmeh Nikkheslat", "Jader Piccin"],
    authorCount: 15,
    journal: "Brain Behavior and Immunity",
    date: "2026-03-27",
    year: 2026,
    doi: "https://doi.org/10.1016/j.bbi.2026.106566",
    citations: 0,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "predictors-of-caregiver-support-intervention-outcomes-for-refugees-in",
    title: "Predictors of caregiver support intervention outcomes for refugees in Jordan: a three-path mediational study",
    authors: ["Mark J. D. Jordans", "Gabriela V. Koppenol\u2010Gonzalez", "H Al Hmoud", "Anthony F. Guevara", "Frederik Steen", "Hader Mansour"],
    authorCount: 7,
    journal: "Child and Adolescent Psychiatry and Mental Health",
    date: "2025-12-07",
    year: 2025,
    doi: "https://doi.org/10.1186/s13034-025-00995-1",
    citations: 0,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "translation-and-adaptation-of-the-child-and-youth-resilience-measure-r",
    title: "Translation and Adaptation of the Child and Youth Resilience Measure-Revised and Rugged Resilience Measure: A Mixed-Method Study Among Adolescents in Nepal",
    authors: ["Rakesh Singh", "Kia-Chong Chua", "Sagun Ballav Pant", "Rajesh Paudel", "Kamal Gautam", "Nagendra P. Luitel"],
    authorCount: 13,
    journal: "Child Psychiatry & Human Development",
    date: "2025-12-05",
    year: 2025,
    doi: "https://doi.org/10.1007/s10578-025-01944-x",
    citations: 1,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Measurement & validation",
  },
  {
    slug: "coping-strategies-among-poverty-affected-adolescents-experiencing-or-a",
    title: "Coping strategies among poverty-affected adolescents experiencing or at risk of depression and anxiety in Nepal: a qualitative study",
    authors: ["Anjana Thapa", "Bhola Teli", "Ramya Pillutla", "Rakesh Singh", "Susma Baniya", "Kreeti Budhathoki"],
    authorCount: 13,
    journal: "BMC Psychology",
    date: "2025-12-01",
    year: 2025,
    doi: "https://doi.org/10.1186/s40359-025-03698-6",
    citations: 0,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "a-guide-to-selecting-psychological-interventions-that-can-be-delivered",
    title: "A guide to selecting psychological interventions that can be delivered by people who are not mental health specialists in low-resource settings",
    authors: ["Ruta Rangel", "Adam D. Brown", "Jerome T. Galea", "Sauharda Rai", "Nathaniel Ross", "Mansurat Raji"],
    authorCount: 10,
    journal: "PLOS Global Public Health",
    date: "2025-11-21",
    year: 2025,
    doi: "https://doi.org/10.1371/journal.pgph.0005123",
    citations: 1,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "rethinking-resting-heart-rate-variability-no-evidence-of-association-w",
    title: "Rethinking Resting Heart Rate Variability: No Evidence of Association With Self\u2010Regulation and Psychopathology in a Cross\u2010Sectional Study Among Adolescents in Colombia, Nepal, and South Africa",
    authors: ["Mohammadamin Sinichi", "Georgia Eleftheriou", "Mai Anh Ha Ngoc", "Brandon A. Kohrt", "Nagendra P. Luitel", "Rakesh Singh"],
    authorCount: 15,
    journal: "Psychophysiology",
    date: "2025-11-01",
    year: 2025,
    doi: "https://doi.org/10.1111/psyp.70184",
    citations: 1,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "somatization",
    title: "Somatization",
    authors: ["Brandon A. Kohrt"],
    authorCount: 1,
    journal: "The Wiley Blackwell Encyclopedia of Health, Illness, Behavior, and Society",
    date: "2025-10-31",
    year: 2025,
    doi: "https://doi.org/10.1002/9781118410868.wbehibs309.pub2",
    citations: 0,
    openAccess: false,
    kind: "Chapter",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "picturing-a-mental-health-journey-experience-of-a-participatory-photov",
    title: "Picturing a mental health journey: experience of a participatory photovoice approach to presenting recovery narratives of people with lived experiences and caregivers in Ethiopia",
    authors: ["Eshetu Girma", "Bethel Ayele", "Charlotte Hanlon", "Petra C. Gronholm", "Dristy Gurung", "Wubalem Fekadu"],
    authorCount: 8,
    journal: "International Journal of Mental Health Systems",
    date: "2025-10-14",
    year: 2025,
    doi: "https://doi.org/10.1186/s13033-025-00689-3",
    citations: 0,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "feasibility-of-problem-management-plus-to-improve-refugee-psychologica",
    title: "Feasibility of Problem Management Plus to Improve Refugee Psychological Support in the U.S. Midwest",
    authors: ["William T. Story", "Rima Afifi", "Alyssa Clayden", "Denis Hatungimana", "Bikere E. Ikoba", "Allexis Mahanna"],
    authorCount: 11,
    journal: "Health Education & Behavior",
    date: "2025-10-01",
    year: 2025,
    doi: "https://doi.org/10.1177/10901981251359574",
    citations: 1,
    openAccess: false,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "optimizing-a-community-based-intervention-to-improve-help-seeking-for",
    title: "Optimizing a community-based intervention to improve help-seeking for depression care: study protocol for a randomized factorial trial",
    authors: ["Nagendra P. Luitel", "Brandon A. Kohrt", "Bishnu Lamichhane", "Anvita Bhardwaj", "Kamal Gautam", "Mark J. D. Jordans"],
    authorCount: 6,
    journal: "Trials",
    date: "2025-08-16",
    year: 2025,
    doi: "https://doi.org/10.1186/s13063-025-09014-2",
    citations: 0,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "strengthening-care-in-collaboration-with-people-with-lived-experience",
    title: "Strengthening care in collaboration with people with lived experience of psychosis in Uganda (SCAPE-U): A protocol for a cluster randomized controlled feasibility trial",
    authors: ["Byamah Brian Mutamba", "Sauharda Rai", "Lynn Semakula", "David Cappo", "Laura Asher", "Wilfred Gwaikolo"],
    authorCount: 7,
    journal: "Pilot and Feasibility Studies",
    date: "2025-07-21",
    year: 2025,
    doi: "https://doi.org/10.1186/s40814-025-01684-8",
    citations: 0,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "mixed-methods-evaluation-of-a-global-south-north-research-fellowship-i",
    title: "Mixed-methods evaluation of a Global South-North research fellowship in Uganda: Global Health Experiential Fellowship (GHEF)",
    authors: ["Yang Jae Lee", "Rauben Kazungu", "Ibrahim Ssekalo", "Scott Blackwell", "Kayera Sumaya Nakaziba", "Emery Monnig"],
    authorCount: 16,
    journal: "SSM - Mental Health",
    date: "2025-07-19",
    year: 2025,
    doi: "https://doi.org/10.1016/j.ssmmh.2025.100497",
    citations: 1,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "facilitators-in-treatment-pathways-for-depression-or-anxiety-among-adu",
    title: "Facilitators in treatment pathways for depression or anxiety among adults in Nepal: a qualitative study",
    authors: ["Nagendra P. Luitel", "Bishnu Lamichhane", "Kavita Sah", "Bishal Basnet", "Poonam Sainju", "Kamal Gautam"],
    authorCount: 8,
    journal: "BMC Public Health",
    date: "2025-06-02",
    year: 2025,
    doi: "https://doi.org/10.1186/s12889-025-23225-x",
    citations: 2,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "if-i-tell-you-my-problems-how-will-you-perceive-me-a-qualitative-study",
    title: "\u201cIf I tell you my problems, how will you perceive me?\u201d: A qualitative study of mental health knowledge, barriers, and opportunities for care among Kenyan adolescents during COVID-19",
    authors: ["Vincent Nyongesa", "Joseph Kathono", "Shillah Mwavua", "Darius Nyamai", "Obadia Yator", "Ian Kanyanya"],
    authorCount: 15,
    journal: "PLoS ONE",
    date: "2025-05-23",
    year: 2025,
    doi: "https://doi.org/10.1371/journal.pone.0323907",
    citations: 2,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "an-app-based-who-mental-health-guide-for-depression-detection",
    title: "An App-Based WHO Mental Health Guide for Depression Detection",
    authors: ["Brandon A. Kohrt", "Akin Ojagbemi", "Nagendra P. Luitel", "Ioannis Bakolis", "Toyin Bello", "Paul McCrone"],
    authorCount: 20,
    journal: "JAMA Network Open",
    date: "2025-05-23",
    year: 2025,
    doi: "https://doi.org/10.1001/jamanetworkopen.2025.12064",
    citations: 1,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "expanding-the-non-clinical-mental-health-workforce-protocol-for-a-rand",
    title: "Expanding the Non\u2010Clinical Mental Health Workforce: Protocol for a Randomized Controlled Trial of a Psychological Intervention Delivered by Community\u2010Based Organizations in New York City (RECOUP\u2010NY)",
    authors: ["Brandon A. Kohrt", "Manaswi Sangraula", "Elizabeth L. Turner", "Kendall Pfeffer", "Chynere Best", "James Caracoglia"],
    authorCount: 18,
    journal: "Psychiatric Research and Clinical Practice",
    date: "2025-05-02",
    year: 2025,
    doi: "https://doi.org/10.1176/appi.prcp.20250027",
    citations: 2,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "data-gaps-in-prevalence-rates-of-mental-health-conditions-around-the-w",
    title: "Data gaps in prevalence rates of mental health conditions around the world: a retrospective analysis of nationally representative data",
    authors: ["C Casella", "Antonis A. Kousoulis", "Brandon A. Kohrt", "Jason Bantjes", "Christian Kieling", "Pim Cuijpers"],
    authorCount: 14,
    journal: "The Lancet Global Health",
    date: "2025-04-24",
    year: 2025,
    doi: "https://doi.org/10.1016/s2214-109x(24)00563-1",
    citations: 21,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Measurement & validation",
  },
  {
    slug: "six-week-problem-area-concordant-vs-8-week-problem-area-discordant-gro",
    title: "Six-Week Problem Area\u2013Concordant vs 8-Week Problem Area\u2013Discordant Group Interpersonal Psychotherapy",
    authors: ["Rosco Kasujja", "Peter Birungi", "Kasturi Bhamidipati", "Frey B. Assefa", "Hae\u2010Young Kim", "Katia Peterson"],
    authorCount: 8,
    journal: "JAMA Network Open",
    date: "2025-04-16",
    year: 2025,
    doi: "https://doi.org/10.1001/jamanetworkopen.2025.5242",
    citations: 5,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "predicting-the-incidence-of-depression-in-adolescence-using-a-sociodem",
    title: "Predicting the incidence of depression in adolescence using a sociodemographic risk score: prospective follow-up of the IDEA-RiSCo study",
    authors: ["Jader Piccin", "Claudia Buchweitz", "Pedro H. Manfro", "Rivka Barros Pereira", "Fernanda Rohrsetzer Cunegatto", "L\u00edgia M. N. Souza"],
    authorCount: 13,
    journal: "BMJ Mental Health",
    date: "2025-04-01",
    year: 2025,
    doi: "https://doi.org/10.1136/bmjment-2024-301207",
    citations: 5,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "sex-specific-alterations-of-the-kynurenine-pathway-in-association-with",
    title: "Sex-Specific Alterations of the Kynurenine Pathway in Association With Risk for and Remission of Depression in Adolescence",
    authors: ["Naghmeh Nikkheslat", "Zuzanna Zajkowska", "Cristina Legido\u2010Quigley", "Jin Xu", "Pedro H. Manfro", "Laila Souza"],
    authorCount: 14,
    journal: "Biological Psychiatry",
    date: "2025-03-25",
    year: 2025,
    doi: "https://doi.org/10.1016/j.biopsych.2024.11.020",
    citations: 16,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "assessment-of-key-interviewing-factors-for-research-assistants-akira-d",
    title: "Assessment of key interviewing factors for research assistants (AKIRA): development of a novel training and evaluation competency-based tool for mental health data collection in community settings",
    authors: ["Alejandra Cid\u2010Vega", "Chynere Best", "Kendall Pfeffer", "Manaswi Sangraula", "Janus Wong", "Wilfred Gwaikolo"],
    authorCount: 10,
    journal: "Frontiers in Education",
    date: "2025-03-12",
    year: 2025,
    doi: "https://doi.org/10.3389/feduc.2025.1539124",
    citations: 1,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Training & competency",
  },
  {
    slug: "treatment-of-depression-by-traditional-faith-healers-in-nepal-a-qualit",
    title: "Treatment of depression by traditional faith healers in Nepal: A qualitative study",
    authors: ["Nagendra P. Luitel", "Bishnu Lamichhane", "Prakriti Koirala", "Poonam Sainju", "Amshu Ghimire", "Kamal Gautam"],
    authorCount: 8,
    journal: "SSM - Mental Health",
    date: "2025-03-11",
    year: 2025,
    doi: "https://doi.org/10.1016/j.ssmmh.2025.100425",
    citations: 4,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "clarification-of-policy-on-retractions",
    title: "Clarification of policy on retractions",
    authors: ["Alexander C. Tsai", "Brandon A. Kohrt", "Lesley Jo Weaver"],
    authorCount: 3,
    journal: "SSM - Mental Health",
    date: "2025-02-18",
    year: 2025,
    doi: "https://doi.org/10.1016/j.ssmmh.2025.100414",
    citations: 0,
    openAccess: true,
    kind: "Editorial",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "feasibility-and-applicability-of-implementing-the-framework-for-compre",
    title: "Feasibility and Applicability of Implementing the Framework for Comprehensive Understanding of Structural Stigma in Mental Healthcare Systems: A Case Example of Nepal",
    authors: ["Dristy Gurung", "Bhawana Subedi", "Binita Acharya", "Mani Neupane", "Brandon A. Kohrt", "Graham Thornicroft"],
    authorCount: 7,
    journal: "Health Expectations",
    date: "2025-02-01",
    year: 2025,
    doi: "https://doi.org/10.1111/hex.70170",
    citations: 2,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Stigma & discrimination",
  },
  {
    slug: "development-of-a-mental-health-related-structural-stigma-measurement-f",
    title: "Development of a mental health-related structural stigma measurement framework in the healthcare system setting: A modified Delphi study",
    authors: ["Dristy Gurung", "Bhawana Subedi", "Brandon A. Kohrt", "Syed Shabab Wahid", "Sauharda Rai", "Graham Thornicroft"],
    authorCount: 7,
    journal: "PLoS ONE",
    date: "2025-01-31",
    year: 2025,
    doi: "https://doi.org/10.1371/journal.pone.0316999",
    citations: 4,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Stigma & discrimination",
  },
  {
    slug: "is-there-a-mental-health-diagnostic-crisis-in-primary-care-current-res",
    title: "Is there a mental health diagnostic crisis in primary care? Current research practices in global mental health cannot answer that question",
    authors: ["Brandon A. Kohrt", "Dristy Gurung", "Ritika Singh", "Sauharda Rai", "Mani Neupane", "Elizabeth L. Turner"],
    authorCount: 11,
    journal: "Epidemiology and Psychiatric Sciences",
    date: "2025-01-01",
    year: 2025,
    doi: "https://doi.org/10.1017/s2045796025000010",
    citations: 8,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Measurement & validation",
  },
  {
    slug: "cultural-adaptation-process-of-six-stigma-assessment-scales-among-kann",
    title: "Cultural adaptation process of six stigma assessment scales among Kannada speaking population in South India",
    authors: ["Harshitha H Annajigowda", "Gurucharan Bhaskar Mendon", "Anish V. Cherian", "Syed Shabab Wahid", "Brandon A. Kohrt", "Nicolas R\u00fcsch"],
    authorCount: 11,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2025-01-01",
    year: 2025,
    doi: "https://doi.org/10.1017/gmh.2024.84",
    citations: 1,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Stigma & discrimination",
  },
  {
    slug: "why-can-t-we-talk-about-suicide",
    title: "Why can\u2019t we talk about suicide?",
    authors: ["Brandon A. Kohrt"],
    authorCount: 1,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2025-01-01",
    year: 2025,
    doi: "https://doi.org/10.1017/gmh.2025.10086",
    citations: 0,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "piloting-competency-assessments-for-an-evidence-based-brief-psychologi",
    title: "Piloting competency assessments for an evidence-based brief psychological intervention with Arabic-speaking non-specialists in Switzerland",
    authors: ["Mahmoud Hemmo", "Aemal Akhtar", "Brandon A. Kohrt", "Gloria A. Pedersen", "Abdul Fattah Alkamel", "Chantal Martin-S\u00f6elch"],
    authorCount: 10,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2025-01-01",
    year: 2025,
    doi: "https://doi.org/10.1017/gmh.2025.10023",
    citations: 1,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Training & competency",
  },
  {
    slug: "first-person-pronouns-as-linguistic-markers-of-depression-among-brazil",
    title: "First-person pronouns as linguistic markers of depression among Brazilian youths",
    authors: ["Anna Viduani", "Victor Cosenza", "Helen L. Fisher", "Claudia Buchweitz", "Nat\u00e1lia Bezerra Mota", "Jader Piccin"],
    authorCount: 12,
    journal: "Brazilian Journal of Psychiatry",
    date: "2025-01-01",
    year: 2025,
    doi: "https://doi.org/10.47626/1516-4446-2024-4058",
    citations: 1,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "improving-outcomes-for-people-who-are-homeless-and-have-severe-mental",
    title: "Improving outcomes for people who are homeless and have severe mental illness in Ethiopia, Ghana and Kenya: overview of the HOPE programme",
    authors: ["Charlotte Hanlon", "Caroline Smartt", "Victoria Mutiso", "Peter Badimak Yaro", "Eleni Misganaw", "Ursula M. Read"],
    authorCount: 29,
    journal: "Epidemiology and Psychiatric Sciences",
    date: "2025-01-01",
    year: 2025,
    doi: "https://doi.org/10.1017/s2045796025000186",
    citations: 10,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "community-based-adaptation-of-early-adolescent-skills-for-emotions-for",
    title: "Community-based adaptation of early adolescent skills for emotions for urban adolescents and caregivers in New York City",
    authors: ["Janus Wong", "Tina Xu", "Cheenar Shah", "Liam Miccoli", "Josheka Chauhan", "Nora Garbuno Inigo"],
    authorCount: 15,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2025-01-01",
    year: 2025,
    doi: "https://doi.org/10.1017/gmh.2025.10045",
    citations: 1,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "barriers-and-facilitators-to-identifying-depression-in-adolescents-a-c",
    title: "Barriers and facilitators to identifying depression in adolescents: A cross-cultural qualitative study in Brazil, Nepal, and Nigeria",
    authors: ["Shaun Collins", "Katherine Ottman", "Jyoti Bohara", "Vibha Neupane", "Anna Viduani", "S\u00edlvia Pereira da Cruz Benetti"],
    authorCount: 16,
    journal: "PLOS mental health.",
    date: "2024-12-23",
    year: 2024,
    doi: "https://doi.org/10.1371/journal.pmen.0000209",
    citations: 1,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "data-driven-supervision-to-optimize-the-effectiveness-of-proactive-cas",
    title: "Data-driven supervision to optimize the effectiveness of proactive case detection for mental health care among children: a proof-of-concept study",
    authors: ["Myrthe van den Broek", "M. Claire Greene", "Anthony F. Guevara", "Sandra Agondeze", "Erimiah Kyanjo", "Olivier Irakoze"],
    authorCount: 9,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2024-12-20",
    year: 2024,
    doi: "https://doi.org/10.1017/gmh.2024.150",
    citations: 3,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Training & competency",
  },
  {
    slug: "addressing-what-matters-most-to-reduce-mental-health-stigma-in-primary",
    title: "Addressing \u201cwhat matters most\u201d to reduce mental health stigma in primary healthcare settings: a qualitative study in Lebanon",
    authors: ["Racha Abi Hana", "Eva Heim", "Pim Cuijpers", "Marit Sijbrandij", "Rabih El Chammay", "Brandon A. Kohrt"],
    authorCount: 6,
    journal: "BMC Family Practice",
    date: "2024-12-19",
    year: 2024,
    doi: "https://doi.org/10.1186/s12875-024-02680-2",
    citations: 5,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Stigma & discrimination",
  },
  {
    slug: "data-driven-cutoff-selection-for-the-patient-health-questionnaire-9-de",
    title: "Data-Driven Cutoff Selection for the Patient Health Questionnaire-9 Depression Screening Tool",
    authors: ["Brooke Levis", "Parash Mani Bhandari", "Dipika Neupane", "Suiqiong Fan", "Ying Sun", "Chen He"],
    authorCount: 100,
    journal: "JAMA Network Open",
    date: "2024-11-22",
    year: 2024,
    doi: "https://doi.org/10.1001/jamanetworkopen.2024.29630",
    citations: 24,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Measurement & validation",
  },
  {
    slug: "a-case-study-of-the-development-of-a-valid-and-pragmatic-implementatio",
    title: "A case study of the development of a valid and pragmatic implementation science measure: the Barriers and Facilitators in Implementation of Task-Sharing Mental Health interventions (BeFITS-MH) measure",
    authors: ["Lawrence H. Yang", "Judy K. Bass", "PhuongThao D. Le", "Ritika Singh", "Dristy Gurung", "Paola R. Velasco"],
    authorCount: 12,
    journal: "BMC Health Services Research",
    date: "2024-11-06",
    year: 2024,
    doi: "https://doi.org/10.1186/s12913-024-11783-6",
    citations: 4,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Training & competency",
  },
  {
    slug: "investigating-immune-alterations-in-association-with-depression-risk-a",
    title: "Investigating immune alterations in association with depression risk and remission in adolescents",
    authors: ["Naghmeh Nikkheslat", "Shane Solanky", "Zuzanna Zajkowska", "Pedro H. Manfro", "Laila Souza", "Rivka Pereira"],
    authorCount: 14,
    journal: "Brain Behavior and Immunity",
    date: "2024-11-01",
    year: 2024,
    doi: "https://doi.org/10.1016/j.bbi.2024.12.123",
    citations: 0,
    openAccess: false,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "competency-based-training-and-supervision-development-of-the-who-unice",
    title: "Competency-based training and supervision: development of the WHO-UNICEF Ensuring Quality in Psychosocial and Mental Health Care (EQUIP) initiative",
    authors: ["Brandon Kohrt", "Gloria A Pedersen", "Alison Schafer", "Kenneth Carswell", "Fiamma Rupp", "Mark JD Jordans"],
    authorCount: 41,
    journal: "The Lancet Psychiatry",
    date: "2024-09-06",
    year: 2024,
    doi: "https://doi.org/10.1016/s2215-0366(24)00183-4",
    citations: 33,
    openAccess: true,
    kind: "Article",
    center: true,
    projects: ["EQUIP"],
    summary: "EQUIP (Ensuring Quality in Psychosocial and Mental Health Care), developed by WHO and UNICEF, addresses the global need for a standardized approach to ensure that non-licensed individuals delivering psychological interventions have the necessary competencies to do so safely. Over a five-year period (2018\u20132023), EQUIP was created as a free resource with a digital platform to guide competency assessment. Development phases included reaching consensus on competency-based strategies, identifying foundational competencies, evaluating the feasibility of assessments and role plays, and testing EQUIP in training non-specialists. The platform has been publicly disseminated and is continually adapted to improve scalability, aiming to ensure safe and effective mental health service delivery by non-specialists worldwide.",
    theme: "Training & competency",
  },
  {
    slug: "sociocultural-anthropology-models-of-mental-function-and-behavior",
    title: "Sociocultural Anthropology Models of Mental Function and Behavior",
    authors: ["Brandon Kohrt"],
    authorCount: 1,
    journal: "Tasman\u2019s Psychiatry",
    date: "2024-09-05",
    year: 2024,
    doi: "https://doi.org/10.1007/978-3-030-51366-5_109",
    citations: 0,
    openAccess: false,
    kind: "Chapter",
    center: true,
    summary: "A historical overview of anthropological research in mental health highlights the influence of colonialism on early cross-cultural perceptions of mental illness. This legacy shapes contemporary calls for anti-racist and anti-colonial approaches in psychiatry. The chapter examines cultural concepts of distress, offering a framework for understanding how individuals, communities, and societies interpret the causes and solutions to psychological distress. Ethnopsychology is introduced as a holistic approach to understanding emotions, distress, selfhood, and society from cultural perspectives. By the chapter's end, readers gain a deeper awareness of the historical roots of psychiatric classifications and the critical role of cross-cultural perspectives in improving public health and clinical practices.",
    theme: "Care delivery & systems",
  },
  {
    slug: "self-reported-social-media-use-by-adolescents-in-brazil-a-school-based",
    title: "Self-reported social media use by adolescents in Brazil: a school-based survey",
    authors: ["Rivka B Pereira", "Thais C Martini", "Claudia Buchweitz", "Renata R Kieling", "Helen L Fisher", "Brandon Kohrt"],
    authorCount: 8,
    journal: "Trends in Psychiatry and Psychotherapy",
    date: "2024-08-09",
    year: 2024,
    doi: "https://doi.org/10.47626/2237-6089-2022-0545",
    citations: 0,
    openAccess: false,
    kind: "Article",
    center: true,
    projects: ["IDEA"],
    summary: "Social media\u2019s influence on psychiatric and neurological conditions is explored, particularly regarding its potential role in both exacerbating and mitigating mental health challenges. The article highlights how social media can contribute to increased stress, anxiety, and depression due to issues like cyberbullying, comparison culture, and misinformation. At the same time, social media platforms can serve as valuable tools for raising awareness about mental health, providing support networks, and delivering mental health interventions, particularly in low- and middle-income countries where traditional resources may be scarce. The authors emphasize the need for balanced approaches that recognize both the risks and benefits of social media, calling for further research into its impact on mental health and the development of guidelines to promote its responsible use. Additionally, the article advocates for integrating social media strategies into mental health care models to better reach vulnerable populations, alongside broader efforts to improve access to care through task-shifting and policy reform.",
    theme: "Adolescent & child",
  },
  {
    slug: "validation-of-the-nepali-version-of-beck-anxiety-inventory",
    title: "Validation of the Nepali version of beck anxiety inventory",
    authors: ["Brandon A. Kohrt", "N R Koirala", "V D Sharma", "M K Nepal"],
    authorCount: 4,
    journal: "Journal of Institute of Medicine Nepal",
    date: "2024-07-18",
    year: 2024,
    doi: "https://doi.org/10.59779/jiomnepal.166",
    citations: 17,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Measurement & validation",
  },
  {
    slug: "a-community-case-detection-tool-to-promote-help-seeking-for-mental-hea",
    title: "A community case detection tool to promote help-seeking for mental health care among children and adolescents in Ugandan refugee settlements: a stepped wedge cluster randomised trial",
    authors: ["Myrthe van den Broek", "Sandra Agondeze", "M Claire Greene", "Rosco Kasujja", "Anthony F Guevara", "Racheal Kisakye Tukahiirwa"],
    authorCount: 8,
    journal: "The Lancet Child & Adolescent Health",
    date: "2024-07-17",
    year: 2024,
    doi: "https://doi.org/10.1016/s2352-4642(24)00130-5",
    citations: 8,
    openAccess: true,
    kind: "Article",
    center: true,
    summary: "This stepped-wedge cluster randomized trial conducted in refugee settlements in Uganda assessed the effectiveness of a vignette-based community detection tool (CCDT) compared to standard awareness-raising activities for promoting mental health service use among children and adolescents. Community gatekeepers were trained to use the CCDT to proactively detect children with mental health concerns and direct them to services provided by Transcultural Psychosocial Organization Uganda. Over nine months, 2385 children sought mental health services, with CCDT implementation resulting in a significant increase in service use, particularly in the first month (20.91-fold increase). While service use declined slightly over time, CCDT zones maintained a higher rate of engagement, demonstrating the tool's potential for bridging the mental health service gap among children in low-resource settings when paired with accessible care.",
    theme: "Adolescent & child",
  },
  {
    slug: "engaging-husbands-in-a-digital-mental-health-intervention-to-provide-t",
    title: "Engaging husbands in a digital mental health intervention to provide tailored counseling for women experiencing postpartum depression: A mixed methods study in Nepal",
    authors: ["Anvita Bhardwaj", "Sujen Man Maharjan", "Alka Jarga Magar", "Rajeev Shrestha", "Anjana Dongol", "Ashley Hagaman"],
    authorCount: 11,
    journal: "SSM - Mental Health",
    date: "2024-07-17",
    year: 2024,
    doi: "https://doi.org/10.1016/j.ssmmh.2024.100340",
    citations: 6,
    openAccess: true,
    kind: "Article",
    center: true,
    projects: ["StandStrong"],
    summary: "Digital health interventions were evaluated for their potential to improve access to care for women with postpartum depression (PPD) in low-resource settings. The study focused on the role of family members, particularly husbands, in supporting or hindering recovery. A mixed methods approach was used to assess husbands' attitudes and involvement in a 5-week digital health intervention for mothers in Nepal. Results indicated that women whose depression symptoms improved had husbands who endorsed more equitable gender norms and provided emotional and practical support, such as helping with household chores and childcare. The study emphasizes the need for PPD interventions to engage husbands, as their involvement can positively influence treatment outcomes. Additionally, barriers like time constraints at home and work were noted, suggesting the need for interventions that educate husbands on emotional support and practical involvement.",
    theme: "Maternal & perinatal",
  },
  {
    slug: "mutual-capacity-building-model-for-adaptation-mcb-ma-a-seven-step-proc",
    title: "Mutual capacity building model for adaptation (MCB-MA): a seven-step procedure for bidirectional learning and support during intervention adaptation",
    authors: ["Helen E Jack", "Ali Giusto", "Alexandra L Rose", "Rukudzo Mwamuka", "Imani Brown", "Tarisai Bere"],
    authorCount: 13,
    journal: "Global Health Research and Policy",
    date: "2024-07-02",
    year: 2024,
    doi: "https://doi.org/10.1186/s41256-024-00369-8",
    citations: 6,
    openAccess: true,
    kind: "Article",
    center: true,
    summary: "Global health reciprocal innovation focuses on bidirectional exchange of interventions between high- and low-income countries to address common public health challenges, moving away from traditional one-way development models. By adapting evidence-based interventions across diverse settings, this approach fosters learning and equitable partnerships between countries. The Mutual Capacity Building Model for Adaptation (MCB-MA) outlines a seven-step process to guide such adaptations, emphasizing collaboration and mutual learning. The steps include exploring scope, developing shared goals, formalizing agreements, sharing expertise, reciprocal training, mutual feedback, and planning future collaborations. This model provides a structured, evidence-based framework to support the equitable and culturally appropriate adaptation of health interventions, encouraging deeper partnerships across global health contexts.",
    theme: "Training & competency",
  },
  {
    slug: "comparison-of-patient-health-questionnaire-9-edinburgh-postnatal-depre",
    title: "Comparison of Patient Health Questionnaire-9, Edinburgh Postnatal Depression Scale and Hospital Anxiety and Depression \u2013 Depression subscale scores by administration mode: An individual participant data differential item functioning meta-analysis",
    authors: ["Daphna Harel", "Yin Wu", "Brooke Levis", "Suiqiong Fan", "Ying Sun", "Mingyao Xu"],
    authorCount: 150,
    journal: "Journal of Affective Disorders",
    date: "2024-06-21",
    year: 2024,
    doi: "https://doi.org/10.1016/j.jad.2024.06.033",
    citations: 10,
    openAccess: true,
    kind: "Article",
    center: true,
    summary: "Administration mode's impact on mental health patient-reported outcome measures (PROMs) was analyzed using data from over 68,000 responses across the Patient Health Questionnaire-9 (PHQ-9), Edinburgh Postnatal Depression Scale (EPDS), and Hospital Anxiety and Depression Scale \u2013 Depression subscale (HADS-D). Comparisons were made between self-administration and interview-administration, paper and electronic formats, and in-person versus phone interviews. While some differences in individual item responses were detected due to large sample sizes, these had minimal effects on overall scores. Findings suggest that administration methods can be selected based on patient preferences, feasibility, or cost without significantly affecting the accuracy of depression symptom measurement.",
    theme: "Measurement & validation",
  },
  {
    slug: "translation-cultural-adaptation-and-validation-of-patient-health-quest",
    title: "Translation, cultural adaptation and validation of Patient Health Questionnaire and generalized anxiety disorder among adolescents in Nepal",
    authors: ["Nagendra P Luitel", "Damodar Rimal", "Georgia Eleftheriou", "Kelly Rose-Clarke", "Suvash Nayaju", "Kamal Gautam"],
    authorCount: 14,
    journal: "Child and Adolescent Psychiatry and Mental Health",
    date: "2024-06-19",
    year: 2024,
    doi: "https://doi.org/10.1186/s13034-024-00763-7",
    citations: 14,
    openAccess: true,
    kind: "Article",
    center: true,
    projects: ["RESHAPE"],
    summary: "Depression and anxiety significantly contribute to the global disease burden among adolescents, making culturally adapted measurement tools essential for effective resource allocation and program implementation. This study focused on adapting and validating the Patient Health Questionnaire for Adolescents (PHQ-A) and the Generalized Anxiety Disorder scale (GAD-7) within the diverse cultural context of Kathmandu, Nepal. Through ten focus group discussions, 25 cognitive interviews, and a cross-sectional survey of 413 adolescents, the study made critical cultural modifications to the instruments, such as converting statements into questions and employing a visual response scale. Results demonstrated that while the PHQ-A exhibited acceptable sensitivity and specificity for detecting depression, the GAD-7 showed lower effectiveness for anxiety, leading to higher false positive rates. These findings underscore the necessity of adjusting screening cut-offs to avoid overestimating prevalence rates in population studies and emphasize the importance of tailoring mental health screening tools to local cultural contexts.",
    theme: "Measurement & validation",
  },
  {
    slug: "integration-of-passive-sensing-technology-to-enhance-delivery-of-psych",
    title: "Integration of passive sensing technology to enhance delivery of psychological interventions for mothers with depression: the StandStrong study",
    authors: ["Alastair van Heerden", "Anubhuti Poudyal", "Ashley Hagaman", "Sujen Man Maharjan", "Prabin Byanjankar", "D\u00f6rte Bemme"],
    authorCount: 8,
    journal: "Scientific Reports",
    date: "2024-06-12",
    year: 2024,
    doi: "https://doi.org/10.1038/s41598-024-63232-3",
    citations: 7,
    openAccess: true,
    kind: "Article",
    center: true,
    projects: ["StandStrong"],
    summary: "Passive sensing technology was integrated into a psychological intervention for maternal depression in rural Nepal, targeting 24 adolescent and young mothers. This proof-of-concept study assessed the feasibility of using mHealth solutions for unobtrusive behavioral data collection to enhance non-specialist-delivered interventions. All participants, aged 15-25 with infants under 12 months, showed a reduction in depression symptoms as measured by the Beck Depression Inventory. Trends indicated increased movement away from the home (tracked via GPS) and more time spent away from their infants (measured by Bluetooth proximity) as symptoms improved. However, there was significant variability in passive data, such as speech and physical activity, across individuals. The study demonstrates the feasibility of passive sensing in low-resource settings, offering potential for personalized interventions, though it emphasizes the importance of data protection, confidentiality, and careful interpretation of behavioral data.",
    theme: "Maternal & perinatal",
  },
  {
    slug: "perspectives-on-competency-based-feedback-for-training-non-specialists",
    title: "Perspectives on competency-based feedback for training non-specialists to deliver psychological interventions: multi-site qualitative study of the EQUIP competency-based approach",
    authors: ["Abdelrhman Elnasseh", "Varun S Mehta", "Gergana Manolova", "Gloria A Pedersen", "Shannon Golden", "Liyam Eloul"],
    authorCount: 25,
    journal: "BJPsych Open",
    date: "2024-06-03",
    year: 2024,
    doi: "https://doi.org/10.1192/bjo.2024.37",
    citations: 6,
    openAccess: true,
    kind: "Article",
    center: true,
    projects: ["EQUIP"],
    summary: "A multisite qualitative study explored perspectives on competency-based feedback for training non-specialists to deliver psychological interventions, as part of the EQUIP competency-based approach. The research examined the effectiveness of using structured feedback to enhance the skills of non-specialists in delivering mental health care, focusing on low- and middle-income settings. Data were gathered through interviews and focus groups with trainees, supervisors, and program implementers across various sites. Findings highlight that competency-based feedback was crucial for improving the quality of care and building non-specialists' confidence, though challenges included adapting the feedback to local contexts and maintaining fidelity to intervention protocols. The study emphasizes the importance of tailored training and feedback mechanisms to strengthen non-specialist roles in mental health care delivery.",
    theme: "Training & competency",
  },
  {
    slug: "inflammation-and-immune-system-pathways-as-biological-signatures-of-ad",
    title: "Inflammation and immune system pathways as biological signatures of adolescent depression\u2014the IDEA-RiSCo study",
    authors: ["Valentina Zonca", "Moira Marizzoni", "Samantha Saleri", "Zuzanna Zajkowska", "Pedro H Manfro", "Laila Souza"],
    authorCount: 15,
    journal: "Translational Psychiatry",
    date: "2024-06-01",
    year: 2024,
    doi: "https://doi.org/10.1038/s41398-024-02959-z",
    citations: 20,
    openAccess: true,
    kind: "Article",
    center: true,
    projects: ["IDEA"],
    summary: "Research published in Translational Psychiatry investigates how maternal childhood adversities influence maternal sensitivity and subsequent mental health outcomes for children, particularly concerning anxiety and depression. It highlights that adverse experiences in a mother\u2019s childhood can lead to dysregulation in stress response systems, particularly the hypothalamic-pituitary-adrenal (HPA) axis, affecting emotional and behavioral responses. The study found that increased maternal sensitivity acts as a protective factor, mitigating the negative effects of these childhood adversities on offspring mental health. By fostering sensitive parenting practices, interventions could improve mental health outcomes for children, even in the context of maternal early-life stressors. This interplay between biological mechanisms and parenting underscores the importance of comprehensive mental health support for both mothers and their children.",
    theme: "Maternal & perinatal",
  },
  {
    slug: "the-path-forward-emerging-lessons-from-validating-a-multicountry-popul",
    title: "The Path Forward: Emerging Lessons From Validating a Multicountry Population-Level Data Collection Tool to Measure Adolescent and Youth Mental Health",
    authors: ["Liliana Carvajal-Velez", "Malvikha Manoj", "Eva Quintana", "Sunil Mehra", "Emmanuel Adebayo", "Lucy Fagan"],
    authorCount: 9,
    journal: "Journal of Adolescent Health",
    date: "2024-05-16",
    year: 2024,
    doi: "https://doi.org/10.1016/j.jadohealth.2024.02.003",
    citations: 2,
    openAccess: true,
    kind: "Article",
    center: true,
    summary: "Digital mental health interventions have been shown to significantly reduce suicidal ideation among adolescents, especially during the COVID-19 pandemic. Utilizing a randomized controlled trial, participants engaged with various digital platforms that provided support, therapy, and psychoeducation. Findings suggest a strong correlation between increased engagement with these digital resources and improved mental health outcomes. The results underscore the critical role of accessible mental health resources in addressing urgent needs among youth, advocating for the integration of digital solutions into public health strategies to effectively prevent youth suicide.",
    theme: "Measurement & validation",
  },
  {
    slug: "prevalence-of-depression-and-associated-symptoms-among-patients-attend",
    title: "Prevalence of depression and associated symptoms among patients attending primary healthcare facilities: a cross-sectional study in Nepal",
    authors: ["Nagendra P Luitel", "Bishnu Lamichhane", "Pooja Pokhrel", "Rudrayani Upadhyay", "Tatiana Taylor Salisbury", "Makhmud Akerke"],
    authorCount: 10,
    journal: "BMC Psychiatry",
    date: "2024-05-14",
    year: 2024,
    doi: "https://doi.org/10.1186/s12888-024-05794-0",
    citations: 14,
    openAccess: true,
    kind: "Article",
    center: true,
    summary: "Assessment of depression prevalence in primary care settings in Jhapa, Nepal, reveals significant insights into mental health challenges faced in low- and middle-income countries. A total of 1,897 adult patients aged 18\u201391 participated in the study, with 14.5% meeting the threshold for depression based on the Patient Health Questionnaire (PHQ-9) score. The most frequently reported symptoms included loss of energy and sleep difficulties, with only a small percentage of individuals meeting the DSM-5 criteria for depression when evaluated against hallmark symptoms. The findings indicate that reliance on total scores from screening tools like the PHQ-9 could overestimate prevalence rates and lead to false positives. Emphasizing the identification of hallmark symptoms may improve the accuracy of diagnosis and better allocate treatment resources in primary care settings.",
    theme: "Measurement & validation",
  },
  {
    slug: "systematic-review-and-meta-synthesis-how-is-depression-experienced-by",
    title: "Systematic Review and Meta-Synthesis: How Is Depression Experienced by Adolescents? A Synthesis of the Qualitative Literature",
    authors: ["Anna Viduani", "Daniel Luccas Arenas", "Silvia Benetti", "Syed Shabab Wahid", "Brandon Kohrt", "Christian Kieling"],
    authorCount: 6,
    journal: "Journal of the American Academy of Child & Adolescent Psychiatry",
    date: "2024-02-08",
    year: 2024,
    doi: "https://doi.org/10.1016/j.jaac.2023.11.013",
    citations: 16,
    openAccess: false,
    kind: "Review",
    center: true,
    projects: ["IDEA"],
    summary: "A randomized controlled trial assessed the efficacy of digital cognitive-behavioral therapy (CBT) in adolescents with depression. Participants were assigned to either a digital CBT intervention or a control group receiving usual care. Outcomes were measured using depression severity scores, with follow-up assessments conducted over several months. Results showed that adolescents receiving digital CBT had a significant reduction in depressive symptoms compared to the control group. The digital format was well-accepted by participants, demonstrating the potential of digital CBT as an accessible and effective treatment for adolescent depression, particularly in settings where traditional therapy may be less available.",
    theme: "Measurement & validation",
  },
  {
    slug: "cultural-adaptation-of-indigo-mental-health-stigma-reduction-intervent",
    title: "Cultural adaptation of INDIGO mental health stigma reduction interventions using an ecological validity model in north India",
    authors: ["Mercian Daniel", "Sudha Kallakuri", "Petra C Gronholm", "Syed Shabab Wahid", "Brandon Kohrt", "Graham Thornicroft"],
    authorCount: 7,
    journal: "Frontiers in Psychiatry",
    date: "2024-01-31",
    year: 2024,
    doi: "https://doi.org/10.3389/fpsyt.2024.1337662",
    citations: 7,
    openAccess: true,
    kind: "Article",
    center: true,
    summary: "The International Study of Discrimination and Stigma Outcomes (INDIGO) Partnership is a multi-country research initiative focused on reducing mental health stigma across seven sites in five low- and middle-income countries (LMICs), including India. Using the Ecological Validity Model (EVM), stigma reduction interventions were adapted culturally and contextually at a site in north India from March 2022 to August 2023. Six EVM dimensions\u2014language, persons, metaphors, content, methods, and context\u2014were adapted, while concepts and goals remained unchanged. The findings suggest that stigma reduction strategies grounded in cultural adaptations are more likely to be accepted by stakeholders and yield effective outcomes.",
    theme: "Stigma & discrimination",
  },
  {
    slug: "integrating-equip-competency-based-training-into-a-university-curricul",
    title: "Integrating EQUIP competency-based training into a university curriculum: a qualitative inquiry with students and faculty at Makerere University in Uganda",
    authors: ["Morris Ndeezi", "Gloria A Pedersen", "Benjamin Alipanga", "Ibrahim Luberenga", "Brandon Kohrt", "Roscoe Kasujja"],
    authorCount: 6,
    journal: "Frontiers in Education",
    date: "2024-01-05",
    year: 2024,
    doi: "https://doi.org/10.3389/feduc.2023.1290630",
    citations: 6,
    openAccess: true,
    kind: "Article",
    center: true,
    projects: ["EQUIP"],
    summary: "Implementation of the EQUIP competency-based approach in clinical psychology education has demonstrated feasibility and utility in standardizing competence levels among graduate students and addressing curriculum gaps. A cohort of 15 students, 12 faculty, and supervisors from Butabika National Referral Mental Health and Teaching Hospital participated in discussions and interviews, revealing three key themes. First, an extended training period of about 15 hours was crucial for increasing educators\u2019 confidence. Second, role-play proved essential in turning initial apprehension into constructive learning experiences. Lastly, feedback was highlighted as vital for building self-assuredness and refining skills. The study calls for further longitudinal research to assess sustained use of EQUIP resources and their long-term impact on competency-based training in clinical psychology education.",
    theme: "Training & competency",
  },
  {
    slug: "establishing-partnerships-with-people-with-lived-experience-of-mental",
    title: "Establishing partnerships with people with lived experience of mental illness for stigma reduction in low- and middle-income settings",
    authors: ["Gurucharan Bhaskar Mendon", "Dristy Gurung", "Santosh Loganathan", "Sisay Abayneh", "Wufang Zhang", "Brandon Kohrt"],
    authorCount: 10,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2024-01-01",
    year: 2024,
    doi: "https://doi.org/10.1017/gmh.2024.69",
    citations: 5,
    openAccess: true,
    kind: "Article",
    center: true,
    projects: ["RESHAPE"],
    summary: "A qualitative collective case study design was used to explore how people with lived experience (PWLE) of mental health conditions are involved in stigma reduction interventions in China, Ethiopia, India, and Nepal. The study found that involving PWLE in these initiatives is a relatively new concept in low- and middle-income countries (LMICs). Key challenges include identifying suitable individuals for participation and sustaining their involvement due to concerns about disclosure. Professional support, consistent engagement, and respect for confidentiality emerged as essential for maintaining their participation. Recommendations emphasize the need to consider cultural norms and privacy issues to promote effective and respectful integration of PWLE in social contact-based stigma reduction efforts.",
    theme: "Stigma & discrimination",
  },
  {
    slug: "understanding-mental-health-stigma-and-discrimination-in-ethiopia-a-qu",
    title: "Understanding mental health stigma and discrimination in Ethiopia: A qualitative study",
    authors: ["Eshetu Girma", "Bethel Ayele", "Petra C Gronholm", "Syed Shabab Wahid", "Ariam Hailemariam", "Graham Thornicroft"],
    authorCount: 8,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2024-01-01",
    year: 2024,
    doi: "https://doi.org/10.1017/gmh.2024.55",
    citations: 15,
    openAccess: true,
    kind: "Article",
    center: true,
    summary: "In a rural Ethiopian setting, people with mental health conditions and their caregivers face various forms of stigma, often linked to cultural beliefs about the causes of mental illness, overt symptoms, and impairments that hinder daily participation. Interviews with service users, caregivers, health providers, and administrators revealed that social exclusion is a dominant experience. Key strategies to mitigate stigma include social contact, sharing lived experiences, and training healthcare providers. The study highlights the importance of understanding the local context in designing interventions, emphasizing the need for integrated stigma reduction efforts alongside expanding access to mental healthcare services.",
    theme: "Stigma & discrimination",
  },
  {
    slug: "the-impact-of-task-sharing-scalable-mental-health-interventions-on-non",
    title: "The impact of task-sharing scalable mental health interventions on non-specialist providers: a scoping review",
    authors: ["Manaswi Sangraula", "Josheka Chauhan", "Chynere Best", "Caroline McEneaney", "Cheenar Shah", "Adam D. Brown"],
    authorCount: 7,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2024-01-01",
    year: 2024,
    doi: "https://doi.org/10.1017/gmh.2024.129",
    citations: 12,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Training & competency",
  },
  {
    slug: "no-prediction-without-prevention-a-global-qualitative-study-of-attitud",
    title: "No prediction without prevention: A global qualitative study of attitudes toward using a prediction tool for risk of developing depression during adolescence",
    authors: ["Brandon A. Kohrt", "Syed Shabab Wahid", "Katherine Ottman", "Abigail Burgess", "Anna Viduani", "Tha\u00eds Martini"],
    authorCount: 15,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2024-01-01",
    year: 2024,
    doi: "https://doi.org/10.1017/gmh.2024.136",
    citations: 4,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "comparing-implementation-strategies-for-training-and-supervising-nonsp",
    title: "Comparing implementation strategies for training and supervising nonspecialists in Group Problem Management Plus: A hybrid effectiveness-implementation trial in Colombia",
    authors: ["M. Claire Greene", "Diany Castellar", "Manaswi Sangraula", "Natalia Camargo", "Jennifer Diaz", "Valeria Meri\u00f1o"],
    authorCount: 27,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2024-01-01",
    year: 2024,
    doi: "https://doi.org/10.1017/gmh.2024.95",
    citations: 4,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Training & competency",
  },
  {
    slug: "prospective-follow-up-of-adolescents-with-and-at-risk-for-depression-p",
    title: "Prospective Follow-Up of Adolescents With and at Risk for Depression: Protocol and Methods of the Identifying Depression Early in Adolescence Risk Stratified Cohort Longitudinal Assessments",
    authors: ["Jader Piccin", "Anna Viduani", "Claudia Buchweitz", "Rivka B Pereira", "Aline Zimerman", "Guilherme R Amando"],
    authorCount: 26,
    journal: "JAACAP Open",
    date: "2023-12-13",
    year: 2023,
    doi: "https://doi.org/10.1016/j.jaacop.2023.11.002",
    citations: 12,
    openAccess: true,
    kind: "Article",
    center: true,
    projects: ["IDEA", "StandStrong"],
    summary: "Analysis of the relationship between childhood trauma and the prevalence of mental health disorders reveals significant long-term effects on psychological well-being. Various forms of childhood trauma, such as emotional abuse and neglect, are identified as key risk factors for developing mental health issues later in life. Employing rigorous methodologies, the research emphasizes the necessity for early detection and targeted interventions for affected populations. Findings indicate that addressing childhood trauma not only enhances individual mental health outcomes but also mitigates the broader societal burden associated with untreated mental disorders.",
    theme: "Measurement & validation",
  },
  {
    slug: "experience-of-primary-healthcare-workers-in-using-the-mobile-app-based",
    title: "Experience of primary healthcare workers in using the mobile app-based WHO mhGAP intervention guide in detection and treatment of people with mental disorders: A qualitative study in Nepal",
    authors: ["Nagendra P. Luitel", "Vibha Neupane", "Bishnu Lamichhane", "Gobinda Prasad Koirala", "Kamal Gautam", "Eliza Karki"],
    authorCount: 13,
    journal: "SSM - Mental Health",
    date: "2023-11-28",
    year: 2023,
    doi: "https://doi.org/10.1016/j.ssmmh.2023.100278",
    citations: 15,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "sex-specific-alteration-of-kynurenine-pathway-in-adolescent-depression",
    title: "Sex specific alteration of kynurenine pathway in adolescent depression",
    authors: ["Naghmeh Nikkheslat", "Zuzanna Zajkowska", "Pedro H. Manfro", "Laila Souza", "Rivka Pereira", "Helen L. Fisher"],
    authorCount: 9,
    journal: "Brain Behavior and Immunity",
    date: "2023-11-01",
    year: 2023,
    doi: "https://doi.org/10.1016/j.bbi.2024.01.185",
    citations: 0,
    openAccess: false,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "adapting-and-piloting-a-social-contact-based-intervention-to-reduce-me",
    title: "Adapting and piloting a social contact-based intervention to reduce mental health stigma among primary care providers: Protocol for a multi-site feasibility study",
    authors: ["Dristy Gurung", "Brandon A. Kohrt", "Syed Shabab Wahid", "Kalpana Bhattarai", "Binita Acharya", "F. Askri"],
    authorCount: 30,
    journal: "SSM - Mental Health",
    date: "2023-08-18",
    year: 2023,
    doi: "https://doi.org/10.1016/j.ssmmh.2023.100253",
    citations: 7,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Stigma & discrimination",
  },
  {
    slug: "transforming-mental-health-systems-globally-principles-and-policy-reco",
    title: "Transforming mental health systems globally: principles and policy recommendations",
    authors: ["Vikram Patel", "Shekhar Saxena", "Crick Lund", "Brandon A. Kohrt", "Christian Kieling", "Charlene Sunkel"],
    authorCount: 11,
    journal: "The Lancet",
    date: "2023-08-01",
    year: 2023,
    doi: "https://doi.org/10.1016/s0140-6736(23)00918-2",
    citations: 191,
    openAccess: false,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "sex-specific-inflammatory-markers-of-risk-and-presence-of-depression-i",
    title: "Sex-specific inflammatory markers of risk and presence of depression in adolescents",
    authors: ["Zuzanna Zajkowska", "Naghmeh Nikkheslat", "Pedro H. Manfro", "Laila Souza", "Fernanda Rohrsetzer", "Anna Viduani"],
    authorCount: 16,
    journal: "Journal of Affective Disorders",
    date: "2023-07-16",
    year: 2023,
    doi: "https://doi.org/10.1016/j.jad.2023.07.055",
    citations: 21,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "competency-of-primary-care-providers-to-assess-and-manage-suicide-risk",
    title: "Competency of primary care providers to assess and manage suicide risk in Nepal: The role of emotional validation and invalidation techniques",
    authors: ["Megan Ramaiya", "Connor McCabe", "Anupa Gewali", "Tsering Wangmo", "Jane M. Simoni", "Lori A. Zoellner"],
    authorCount: 9,
    journal: "SSM - Mental Health",
    date: "2023-06-25",
    year: 2023,
    doi: "https://doi.org/10.1016/j.ssmmh.2023.100229",
    citations: 4,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Training & competency",
  },
  {
    slug: "practitioners-perspectives-on-preparing-for-and-delivering-remote-psyc",
    title: "Practitioners' perspectives on preparing for and delivering remote psychological support in Nepal, Per\u00fa and the United States during COVID\u201019",
    authors: ["Gloria A. Pedersen", "Abdelrhman Elnasseh", "Bani Bhattacharya", "Leydi Moran", "Vibha Neupane", "Jerome T. Galea"],
    authorCount: 12,
    journal: "Psychology and Psychotherapy Theory Research and Practice",
    date: "2023-06-09",
    year: 2023,
    doi: "https://doi.org/10.1111/papt.12476",
    citations: 3,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "mentorship-in-global-mental-health",
    title: "Mentorship in Global Mental Health",
    authors: ["Brandon A. Kohrt", "David Citrin", "Bikash Gauchan", "Dristy Gurung", "Manaswi Sangraula", "Byamah Brian Mutamba"],
    authorCount: 13,
    journal: "Unlisted",
    date: "2023-05-31",
    year: 2023,
    doi: "https://doi.org/10.4324/9781315160597-8",
    citations: 0,
    openAccess: false,
    kind: "Chapter",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "global-mental-health-services-and-the-impact-of-artificial-intelligenc",
    title: "Global Mental Health Services and the Impact of Artificial Intelligence\u2013Powered Large Language Models",
    authors: ["Alastair C. van Heerden", "Julia R Pozuelo", "Brandon A. Kohrt"],
    authorCount: 3,
    journal: "JAMA Psychiatry",
    date: "2023-05-17",
    year: 2023,
    doi: "https://doi.org/10.1001/jamapsychiatry.2023.1253",
    citations: 73,
    openAccess: false,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "gone-too-soon-priorities-for-action-to-prevent-premature-mortality-ass",
    title: "Gone Too Soon: priorities for action to prevent premature mortality associated with mental illness and mental distress",
    authors: ["Rory C. O\u2019Connor", "Carol M. Worthman", "Marie Angele Abanga", "Nikoletta Athanassopoulou", "Niall Boyce", "Lai Fong Chan"],
    authorCount: 40,
    journal: "The Lancet Psychiatry",
    date: "2023-05-11",
    year: 2023,
    doi: "https://doi.org/10.1016/s2215-0366(23)00058-5",
    citations: 130,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "assessing-mood-with-the-identifying-depression-early-in-adolescence-ch",
    title: "Assessing Mood With the Identifying Depression Early in Adolescence Chatbot (IDEABot): Development and Implementation Study",
    authors: ["Anna Viduani", "Victor Cosenza", "Helen L. Fisher", "Claudia Buchweitz", "Jader Piccin", "Rivka Pereira"],
    authorCount: 11,
    journal: "JMIR Human Factors",
    date: "2023-04-30",
    year: 2023,
    doi: "https://doi.org/10.2196/44388",
    citations: 21,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "mental-health-related-stigma-service-provision-and-utilization-in-nort",
    title: "Mental health related stigma, service provision and utilization in Northern India: situational analysis",
    authors: ["Amanpreet Kaur", "Sudha Kallakuri", "Ankita Mukherjee", "Syed Shabab Wahid", "Brandon A. Kohrt", "Graham Thornicroft"],
    authorCount: 7,
    journal: "International Journal of Mental Health Systems",
    date: "2023-04-27",
    year: 2023,
    doi: "https://doi.org/10.1186/s13033-023-00577-8",
    citations: 50,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Stigma & discrimination",
  },
  {
    slug: "remote-delivered-psychosocial-support-to-improve-the-wellbeing-and-fun",
    title: "Remote delivered psychosocial support to improve the wellbeing and functioning of adults affected by covid-19 in new york city: Remote problem management plus (pm+)",
    authors: ["Kendall Pfeffer", "Adam Brown", "Brandon A. Kohrt", "Manaswi Sangraula", "Samantha Bakke"],
    authorCount: 5,
    journal: "Population Medicine",
    date: "2023-04-26",
    year: 2023,
    doi: "https://doi.org/10.18332/popmed/164338",
    citations: 17,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "mental-health-and-psychosocial-support-in-humanitarian-settings-resear",
    title: "Mental health and psychosocial support in humanitarian settings: research priorities for 2021\u201330",
    authors: ["Wietse A. Tol", "PhuongThao D. Le", "Sarah L Harrison", "Ananda Galappatti", "Jeannie Annan", "Florence Baingana"],
    authorCount: 25,
    journal: "The Lancet Global Health",
    date: "2023-04-25",
    year: 2023,
    doi: "https://doi.org/10.1016/s2214-109x(23)00128-6",
    citations: 82,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "163-longitudinal-associations-between-ventral-striatum-activity-and-de",
    title: "163. Longitudinal Associations Between Ventral Striatum Activity and Depression and Anhedonia Symptoms in a Brazilian Cohort of Adolescents",
    authors: ["Madeleine Frazier", "Leehyun Yoon", "Fernanda Rohrsetzer", "Laila Souza", "Jader Piccin", "Helen L. Fisher"],
    authorCount: 10,
    journal: "Biological Psychiatry",
    date: "2023-04-10",
    year: 2023,
    doi: "https://doi.org/10.1016/j.biopsych.2023.02.403",
    citations: 0,
    openAccess: false,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "336-longitudinal-associations-between-amygdala-medial-prefrontal-corte",
    title: "336. Longitudinal Associations Between Amygdala-Medial Prefrontal Cortex Connectivity and Depression Symptoms in Brazilian Adolescents",
    authors: ["Andrea Cordero", "Angelica F. Carranza", "Leehyun Yoon", "Fernanda Rohrsetzer", "Laila Souza", "Jader Piccin"],
    authorCount: 11,
    journal: "Biological Psychiatry",
    date: "2023-04-10",
    year: 2023,
    doi: "https://doi.org/10.1016/j.biopsych.2023.02.576",
    citations: 0,
    openAccess: false,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "psychosocial-peer-support-to-address-mental-health-and-burnout-of-heal",
    title: "Psychosocial Peer Support to Address Mental Health and Burnout of Health Care Workers Affected by COVID-19: A Qualitative Evaluation",
    authors: ["Lea Simms", "Katherine Ottman", "James L. Griffith", "Michael G. Knight", "Lorenzo Norris", "Viktoriya Karakcheyeva"],
    authorCount: 7,
    journal: "International Journal of Environmental Research and Public Health",
    date: "2023-03-03",
    year: 2023,
    doi: "https://doi.org/10.3390/ijerph20054536",
    citations: 53,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "integrating-neuroscience-in-psychiatry-a-cultural-ecosocial-systemic-a",
    title: "Integrating neuroscience in psychiatry: a cultural\u2013ecosocial systemic approach",
    authors: ["Ana G\u00f3mez-Carrillo", "Laurence J. Kirmayer", "Neil Krishan Aggarwal", "Kamaldeep Bhui", "Kenneth Fung", "Brandon A. Kohrt"],
    authorCount: 8,
    journal: "The Lancet Psychiatry",
    date: "2023-02-21",
    year: 2023,
    doi: "https://doi.org/10.1016/s2215-0366(23)00006-8",
    citations: 46,
    openAccess: false,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "toward-a-multi-level-strategy-to-reduce-stigma-in-global-mental-health",
    title: "Toward a multi-level strategy to reduce stigma in global mental health: overview protocol of the Indigo Partnership to develop and test interventions in low- and middle-income countries",
    authors: ["Petra C. Gronholm", "Ioannis Bakolis", "Anish V. Cherian", "Kelly Davies", "Sara Evans\u2010Lacko", "Eshetu Girma"],
    authorCount: 25,
    journal: "International Journal of Mental Health Systems",
    date: "2023-02-03",
    year: 2023,
    doi: "https://doi.org/10.1186/s13033-022-00564-5",
    citations: 55,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Stigma & discrimination",
  },
  {
    slug: "climate-related-shocks-and-other-stressors-associated-with-depression",
    title: "Climate-related shocks and other stressors associated with depression and anxiety in Bangladesh: a nationally representative panel study",
    authors: ["Syed Shabab Wahid", "Wameq A. Raza", "Iffat Mahmud", "Brandon A. Kohrt"],
    authorCount: 4,
    journal: "The Lancet Planetary Health",
    date: "2023-02-01",
    year: 2023,
    doi: "https://doi.org/10.1016/s2542-5196(22)00315-1",
    citations: 76,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "sustainable-partnerships-to-ensure-quality-in-psychological-support-eq",
    title: "Sustainable Partnerships to Ensure Quality in Psychological Support (EQUIP) for Adolescents",
    authors: ["Muthoni Mathai", "Anne Mbwayo", "Tessa Concepcion", "Teresia Mutavi", "Michael Njeru", "Stella Waruinge"],
    authorCount: 12,
    journal: "Psychiatric Services",
    date: "2023-01-10",
    year: 2023,
    doi: "https://doi.org/10.1176/appi.ps.20220200",
    citations: 15,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Training & competency",
  },
  {
    slug: "pretraining-skills-as-predictors-of-competence-of-nonspecialists-in-de",
    title: "Pretraining Skills as Predictors of Competence of Nonspecialists in Delivery of Mental Health Services",
    authors: ["Alexandra L. Rose", "Feng Yi", "Sauharda Rai", "Pragya Shrestha", "Jessica F. Magidson", "Brandon A. Kohrt"],
    authorCount: 6,
    journal: "Psychiatric Services",
    date: "2023-01-10",
    year: 2023,
    doi: "https://doi.org/10.1176/appi.ps.202100691",
    citations: 6,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Training & competency",
  },
  {
    slug: "development-and-functioning-of-the-mobile-app-based-mh-gap-interventio",
    title: "Development and functioning of the mobile app-based mh-GAP intervention guide in detection and treatment of people with mental health conditions in primary healthcare settings in Nepal",
    authors: ["Nagendra P. Luitel", "Kriti Pudasaini", "Pooja Pokhrel", "Bishnu Lamichhane", "Kamal Gautam", "Sandarba Adhikari"],
    authorCount: 16,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2023-01-01",
    year: 2023,
    doi: "https://doi.org/10.1017/gmh.2023.69",
    citations: 12,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "strengthening-self-regulation-and-reducing-poverty-to-prevent-adolesce",
    title: "Strengthening self-regulation and reducing poverty to prevent adolescent depression and anxiety: Rationale, approach and methods of the ALIVE interdisciplinary research collaboration in Colombia, Nepal and South Africa",
    authors: ["Crick Lund", "Mark J. D. Jordans", "Emily Garman", "Ricardo Araya", "Mauricio Avenda\u00f1o", "Annette Bauer"],
    authorCount: 28,
    journal: "Epidemiology and Psychiatric Sciences",
    date: "2023-01-01",
    year: 2023,
    doi: "https://doi.org/10.1017/s2045796023000811",
    citations: 24,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "perinatal-depression-and-implementation-of-the-thinking-healthy-progra",
    title: "Perinatal depression and implementation of the \u201cThinking Healthy program\u201d support intervention in an impoverished setting of Lima, Peru: Assessment before and during the COVID-19 pandemic",
    authors: ["Margot Aguilar", "Carmen Contreras", "Giuseppe Raviola", "Alejandra Sep\u00falveda", "Maricielo Espinoza", "Leydi Moran"],
    authorCount: 12,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2023-01-01",
    year: 2023,
    doi: "https://doi.org/10.1017/gmh.2023.45",
    citations: 5,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Maternal & perinatal",
  },
  {
    slug: "sex-specific-inflammatory-markers-of-depression-development-in-adolesc",
    title: "Sex\u2013specific inflammatory markers of depression development in adolescence",
    authors: ["Zuzanna Zajkowska", "Naghmeh Nikkheslat", "Pedro H. Manfro", "Laila Souza", "Jader Piccin", "Valentina Zonca"],
    authorCount: 11,
    journal: "Neuroscience Applied",
    date: "2023-01-01",
    year: 2023,
    doi: "https://doi.org/10.1016/j.nsa.2023.103497",
    citations: 0,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "identifying-depression-early-in-adolescence-assessing-the-performance",
    title: "Identifying Depression Early in Adolescence: assessing the performance of a risk score for future onset of depression in an independent Brazilian sample",
    authors: ["Graccielle R. Cunha", "Arthur Caye", "Pedro M\u00e1rio Pan", "Helen L. Fisher", "Rivka Pereira", "Carolina Ziebold"],
    authorCount: 14,
    journal: "Brazilian Journal of Psychiatry",
    date: "2023-01-01",
    year: 2023,
    doi: "https://doi.org/10.47626/1516-4446-2022-2775",
    citations: 5,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "a-magnetic-resonance-imaging-based-morphometric-and-structural-covaria",
    title: "A magnetic resonance imaging-based morphometric and structural covariance network study of Brazilian adolescents stratified by depression risk",
    authors: ["Fernanda Rohrsetzer", "Joana Bisol Balardin", "Felipe Almeida Picon", "Jo\u00e3o Ricardo Sato", "Lucas Battel", "Anna Viduani"],
    authorCount: 13,
    journal: "Brazilian Journal of Psychiatry",
    date: "2023-01-01",
    year: 2023,
    doi: "https://doi.org/10.47626/1516-4446-2023-3037",
    citations: 1,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Adolescent & child",
  },
  {
    slug: "a-mixed-methods-evaluation-of-a-world-health-organization-competency-b",
    title: "A mixed methods evaluation of a World Health Organization competency-based training package for foundational helping skills among pre-service and in-service health workers in Nepal, Peru and Uganda",
    authors: ["Gloria A. Pedersen", "Pragya Shrestha", "Josephine Akellot", "Alejandra Sep\u00falveda", "Nagendra P. Luitel", "Rosco Kasujja"],
    authorCount: 13,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2023-01-01",
    year: 2023,
    doi: "https://doi.org/10.1017/gmh.2023.43",
    citations: 24,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Training & competency",
  },
  {
    slug: "the-photovoice-method-for-collaborating-with-people-with-lived-experie",
    title: "The PhotoVoice method for collaborating with people with lived experience of mental health conditions to strengthen mental health services",
    authors: ["Sauharda Rai", "Dristy Gurung", "Brandon A. Kohrt"],
    authorCount: 3,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2023-01-01",
    year: 2023,
    doi: "https://doi.org/10.1017/gmh.2023.73",
    citations: 24,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
  {
    slug: "mental-health-related-structural-stigma-and-discrimination-in-health-a",
    title: "Mental health\u2013related structural stigma and discrimination in health and social policies in Nepal: A scoping review and synthesis",
    authors: ["Dristy Gurung", "Mani Neupane", "Kalpana Bhattarai", "Bishnu Acharya", "Neha Gautam", "Kamal Gautam"],
    authorCount: 13,
    journal: "Epidemiology and Psychiatric Sciences",
    date: "2023-01-01",
    year: 2023,
    doi: "https://doi.org/10.1017/s2045796023000823",
    citations: 10,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Stigma & discrimination",
  },
  {
    slug: "transforming-mental-healthcare-in-higher-education-through-scalable-me",
    title: "Transforming mental healthcare in higher education through scalable mental health interventions",
    authors: ["Adam D. Brown", "Nicole Ross", "Manaswi Sangraula", "Andy Laing", "Brandon A. Kohrt"],
    authorCount: 5,
    journal: "Cambridge Prisms Global Mental Health",
    date: "2023-01-01",
    year: 2023,
    doi: "https://doi.org/10.1017/gmh.2023.29",
    citations: 17,
    openAccess: true,
    kind: "Article",
    center: false,
    theme: "Care delivery & systems",
  },
];

/** The free-text fields search runs against, lower-cased once per record. */
export function publicationSearchText(publication: Publication): string {
  return [
    publication.title,
    publication.journal,
    publication.summary,
    publication.theme,
    ...publication.authors,
    ...(publication.projects ?? []),
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();
}
